In [1]:
#!pip install tensorflow-gpu
#import warnings
#warnings.filterwarnings("ignore")

In [2]:
import tensorflow as tf 
print(tf.__version__)

2025-02-23 22:11:07.586061: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-02-23 22:11:07.604711: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-02-23 22:11:07.610334: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-23 22:11:07.623823: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-02-23 22:11:10.085703: W tensorflow/compiler/tf2

2.17.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
## sentences 
sent = ['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am good boy','I am a good developer', 
       'understand the meaning of word', 'your videos are good']

In [5]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

In [6]:
# vocabulary size 
voc_size = 500 

In [7]:
# One Hot encoding representation 
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[121, 239, 185, 250], [121, 239, 185, 254], [121, 344, 185, 441], [380, 469, 97, 127], [380, 469, 107, 97, 142], [112, 121, 120, 185, 286], [467, 463, 356, 97]]


In [8]:
# Word embedding Representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 

In [9]:
import numpy as np 

In [21]:
# Pre paddings 
sent_length = 7 
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

In [22]:
print(embedded_docs.shape)
print(embedded_docs)

(7, 7)
[[  0   0   0 121 239 185 250]
 [  0   0   0 121 239 185 254]
 [  0   0   0 121 344 185 441]
 [  0   0   0 380 469  97 127]
 [  0   0 380 469 107  97 142]
 [  0   0 112 121 120 185 286]
 [  0   0   0 467 463 356  97]]


In [23]:
## 10 feature dimensions 
dim = 8

In [24]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
#model.add(Embedding(input_dim=voc_size, output_dim=10))
model.compile(optimizer='adam',loss='mse')


/nfs/cms/mtech23/lute.gaurav/.local/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [25]:
#model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
## the glass of milk 
embedded_docs[0]

array([  0,   0,   0, 121, 239, 185, 250], dtype=int32)

In [27]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[ 0.04172588,  0.0048405 , -0.00235168, -0.02129643,  0.01162703,
        -0.01159205,  0.00973871, -0.01873662,  0.00043304,  0.02084306],
       [ 0.04172588,  0.0048405 , -0.00235168, -0.02129643,  0.01162703,
        -0.01159205,  0.00973871, -0.01873662,  0.00043304,  0.02084306],
       [ 0.04172588,  0.0048405 , -0.00235168, -0.02129643,  0.01162703,
        -0.01159205,  0.00973871, -0.01873662,  0.00043304,  0.02084306],
       [-0.02086743,  0.04121098, -0.04819726, -0.01867306,  0.00362615,
        -0.04706925, -0.03109208,  0.0478411 , -0.00485798, -0.04634355],
       [-0.02462319,  0.04119672,  0.02620644, -0.0235812 , -0.02261945,
         0.03324081,  0.02540464, -0.04252223, -0.01911665,  0.04778722],
       [-0.00758795, -0.00599672, -0.03042514, -0.00130515, -0.0373156 ,
         0.04796232,  0.02755426, -0.01876959, -0.00225281, -0.04783616],
       [-0.01216642, -0.04756131,  0.04121746, -0.00610895,  0.03401281,
         0.03472355, -0.0349969 , -0.01400433

In [28]:
print(embedded_docs.shape)


(7, 7)


In [33]:
embedded_docs = np.array(embedded_docs)  # Ensure NumPy array
print("Final Shape for Prediction:", embedded_docs.shape) 
print(model.predict(embedded_docs))

Final Shape for Prediction: (7, 7)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[[ 0.00993454 -0.04581786  0.04806477 -0.04189986 -0.03700905
    0.03824917  0.02078705  0.0065341   0.00269305 -0.00790707]
  [ 0.00993454 -0.04581786  0.04806477 -0.04189986 -0.03700905
    0.03824917  0.02078705  0.0065341   0.00269305 -0.00790707]
  [ 0.00993454 -0.04581786  0.04806477 -0.04189986 -0.03700905
    0.03824917  0.02078705  0.0065341   0.00269305 -0.00790707]
  [-0.04750485 -0.01232783 -0.01737478  0.01961798  0.01323592
    0.0431595   0.01690927 -0.04283195 -0.01552646  0.00680237]
  [ 0.00221919 -0.0222248   0.04513028  0.00037787 -0.03871163
    0.04953713 -0.04122846  0.02239246 -0.01105083 -0.03169863]
  [ 0.00792401 -0.03404925  0.00553865  0.00904072 -0.00644469
    0.01307651 -0.0486964   0.04187579  0.00228802  0.00252291]
  [ 0.03965667 -0.01503011 -0.00933828  0.02365159 -0.00878169
    0.04281202 -0.02665956  0.0376229  -0.04404181  0.00601032]]

 [[ 0.00993454 -0.04581786  0.048064

In [34]:
embedded_docs[0]

array([  0,   0,   0, 121, 239, 185, 250], dtype=int32)

In [35]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[ 0.00993454 -0.04581786  0.04806477 -0.04189986 -0.03700905  0.03824917
   0.02078705  0.0065341   0.00269305 -0.00790707]
 [ 0.00993454 -0.04581786  0.04806477 -0.04189986 -0.03700905  0.03824917
   0.02078705  0.0065341   0.00269305 -0.00790707]
 [ 0.00993454 -0.04581786  0.04806477 -0.04189986 -0.03700905  0.03824917
   0.02078705  0.0065341   0.00269305 -0.00790707]
 [-0.04750485 -0.01232783 -0.01737478  0.01961798  0.01323592  0.0431595
   0.01690927 -0.04283195 -0.01552646  0.00680237]
 [ 0.00221919 -0.0222248   0.04513028  0.00037787 -0.03871163  0.04953713
  -0.04122846  0.02239246 -0.01105083 -0.03169863]
 [ 0.00792401 -0.03404925  0.00553865  0.00904072 -0.00644469  0.01307651
  -0.0486964   0.04187579  0.00228802  0.00252291]
 [ 0.03965667 -0.01503011 -0.00933828  0.02365159 -0.00878169  0.04281202
  -0.02665956  0.0376229  -0.04404181  0.00601032]]


- The inner list represents the embeddings vector for a words.
- Values close to 0 --> Word is less important a single word in a learned space.
- Positive/Negative values --> Indicates different relationships in vector space.